api/urls.py
from django.urls import path, include
from .views import ProductList, ProductDetail

urlpatterns = [
    path('v1/products/', ProductList.as_view(), name='productList'),
    path('v1/products/<str:code>', ProductDetail.as_view(), name='productDetail'),
]

appCYF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as authViews
from bases.views import Home, HomeNoPermission

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', authViews.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('logout/', authViews.LogoutView.as_view(template_name='bases/login.html'),
        name='logout'),
    path('noPermission/', HomeNoPermission.as_view(), name='noPermission')
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

class ModelClass(models.Model):
    status = models.BooleanField(default=True)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    userCreator = models.ForeignKey(User, on_delete=models.CASCADE)
    userModifier = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

class ModelClass2(models.Model):
    status = models.BooleanField(default=True)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    userCreator = UserForeignKey(auto_user_add=True, related_name='+')
    userModifier = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract = True

bases/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class MixinFormInvalid:
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

class NoPermission(LoginRequiredMixin, PermissionRequiredMixin, MixinFormInvalid):
    login_url = 'bases:login'
    raise_exception = False
    redirect_field_name = "redirect_to"
    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user == AnonymousUser():
            self.login_url = 'bases:noPermission'
        return HttpResponseRedirect(reverse_lazy(self.login_url))

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

class HomeNoPermission(generic.TemplateView):
    template_name = "bases/nopermission.html"

bases/templates/bases/home.html
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %} {% block side_bar %}{% endblock side_bar %} {% block top_bar %}{% endblock top_bar %} {% block page_content %}{% endblock page_content %} {% block footer %}{% endblock footer %} {% block login %}
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    <small class="text-danger">
                                        {% if  form.errors %}
                                            {% for field in form %}
                                                {% if field.errors %}
                                                    {% for error in field.errors %}
                                                        {{ error|escape }}
                                                    {% endfor %}
                                                {% endif %}
                                            {% endfor %}

                                            {% if form.non_field_errors %}
                                                {% for error in form.non_field_errors %}
                                                    {{ error|escape }}
                                                {% endfor %}
                                            {% endif %}
                                        {% endif %}
                                    </small>
                                </div>
                                <form class="user" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Enter Your Username...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                                    </div>
                                    {#{ form.as_p }#}
                                    <button type="submit" class="btn btn-primary btn-user btn-block">Log in</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock login %}

bases/templates/bases/noPermission.html
{% extends 'base/base.html' %}
{% block page_content %}
<center>
<div class="col-xl-6 col-md-6 mb-6">
    <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        <center><h4> User: <mark>{{ user.username }} {{ user.get_full_name }}</mark></h4></center>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <p>You do not have enough permissions to load the requested option.</p>
                        <br>
                        <small>For being able to load this content you need to be a superuser.</small>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <center>
                                <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Home</a>
                                <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Change user</a>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-exclamation-triangle fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
</center>
{% endblock %}