api/urls.py
from django.urls import path, include
from .views import ProductList, ProductDetail

urlpatterns = [
    path('v1/products/', ProductList.as_view(), name='productList'),
    path('v1/products/<str:code>', ProductDetail.as_view(), name='productDetail'),
]

appCYF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

inventario/urls.py
from django.urls import path
from .views import CategoryView, NewCategory,UpdateCategory, DeleteCategory, \
    SubcategoryView, NewSubcategory, UpdateSubcategory, DeleteSubcategory, \
    BrandView, NewBrand, UpdateBrand, activateBrand,deactivateBrand, \
    MeasurementUnitsView, NewMeasurementUnits, UpdateMeasurementUnits, activateMeasurementUnits,deactivateMeasurementUnits, \
    ProductView, NewProduct, UpdateProduct, activateProduct, deactivateProduct

urlpatterns = [
    path('categories/', CategoryView.as_view(), name='categoryList'),
    path('categories/new', NewCategory.as_view(), name='newCategory'),
    path('categories/edit/<int:pk>', UpdateCategory.as_view(), name='updateCategory'),
    path('categories/delete/<int:pk>', DeleteCategory.as_view(), name='deleteCategory'),

    path('subcategories/', SubcategoryView.as_view(), name='subcategoryList'),
    path('subcategories/new', NewSubcategory.as_view(), name='newSubcategory'),
    path('subcategories/edit/<int:pk>', UpdateSubcategory.as_view(), name='updateSubcategory'),
    path('subcategories/delete/<int:pk>', DeleteSubcategory.as_view(), name='deleteSubcategory'),

    path('brand/', BrandView.as_view(), name='brandList'),
    path('brand/new', NewBrand.as_view(), name='newBrand'),
    path('brand/edit/<int:pk>', UpdateBrand.as_view(), name='updateBrand'),
    path('brand/activate/<int:id>', activateBrand, name='activateBrand'),
    path('brand/deactivate/<int:id>', deactivateBrand, name='deactivateBrand'),

    path('measurementUnits/', MeasurementUnitsView.as_view(), name='measurementUnitsList'),
    path('measurementUnits/new', NewMeasurementUnits.as_view(), name='newMeasurementUnits'),
    path('measurementUnits/edit/<int:pk>', UpdateMeasurementUnits.as_view(), name='updateMeasurementUnits'),
    path('measurementUnits/activate/<int:id>', activateMeasurementUnits, name='activateMeasurementUnits'),
    path('measurementUnits/deactivate/<int:id>', deactivateMeasurementUnits, name='deactivateMeasurementUnits'),

    path('product/', ProductView.as_view(), name='productList'),
    path('product/new', NewProduct.as_view(), name='newProduct'),
    path('product/edit/<int:pk>', UpdateProduct.as_view(), name='updateProduct'),
    path('product/activate/<int:id>', activateProduct, name='activateProduct'),
    path('product/deactivate/<int:id>', deactivateProduct, name='deactivateProduct'),
]

inventario/models.py
from django.db import models
from bases.models import ModelClass

# Create your models here.
class Category(ModelClass):
    description = models.CharField(
        max_length=100,
        help_text='Description',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.description)
    
    def save(self):
        self.description = self.description.upper()
        super(Category, self).save()

    class Meta:
        verbose_name_plural = "Categories"

class Subcategory(ModelClass):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(
        max_length=100,
        help_text='Category Description'
    )

    def __str__(self):
        return '{}:{}'.format(self.category.description, self.description)

    def save(self):
        self.description = self.description.upper()
        super(Subcategory, self).save()

    class Meta:
        verbose_name_plural = "Subcategories"
        unique_together = ('category', 'description')

class Brand(ModelClass):
    description = models.CharField(
        max_length=100,
        help_text="Brand Description",
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(Brand, self).save()

    class Meta:
        verbose_name_plural = "Brands"

class MeasurementUnits(ModelClass):
    description = models.CharField(
        max_length=100,
        help_text="Brand Description",
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(MeasurementUnits, self).save()

    class Meta:
        verbose_name_plural = "Measurement Units"

class Product(ModelClass):
    code = models.CharField(
        max_length=20,
        unique=True
    )
    barCode = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)
    lastPurchase = models.DateField(null=True, blank=True)
    
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    measurementUnits = models.ForeignKey(MeasurementUnits, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(Product, self).save()

    class Meta: 
        verbose_name_plural = "Products"
        unique_together = ('code', 'barCode')

inventario/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Category, Subcategory, Brand, MeasurementUnits, Product
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import CategoryForm, SubcategoryForm, BrandForm, MeasurementUnitsForm, ProductForm
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from bases.views import NoPermission
from django.contrib.auth.decorators import login_required, permission_required
import json

class CategoryView(NoPermission, generic.ListView):
    permission_required = "inventario.view_category"
    model = Category
    template_name = 'inventario/categoryList.html'
    context_object_name = "obj"

class NewCategory(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "inventario.add_category"
    model = Category
    template_name = "inventario/categoryForm.html"
    context_object_name = "obj"
    form_class = CategoryForm
    success_url = reverse_lazy("inventario:categoryList")
    success_message="Category Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class UpdateCategory(SuccessMessageMixin, NoPermission, generic.UpdateView):
    permission_required = "inventario.change_category"
    model = Category
    template_name = "inventario/categoryForm.html"
    context_object_name = "obj"
    form_class = CategoryForm
    success_url = reverse_lazy("inventario:categoryList")
    success_message="Category Successfully Updated"
    
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

class DeleteCategory(NoPermission, generic.DeleteView):
    permission_required = "inventario.delete_category"
    model = Category
    template_name = 'inventario/deleteCategory.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inventario:categoryList')

class SubcategoryView(NoPermission, generic.ListView):
    permission_required = "inventario.view_subcategory"
    model = Subcategory
    template_name = 'inventario/subcategoryList.html'
    context_object_name = "obj"

class NewSubcategory(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "inventario.add_subcategory"
    model = Subcategory
    template_name = "inventario/subcategoryForm.html"
    context_object_name = "obj"
    form_class = SubcategoryForm
    success_url = reverse_lazy("inventario:subcategoryList")
    login_url = "bases:login"
    success_message="Subcategory Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class UpdateSubcategory(SuccessMessageMixin, NoPermission, generic.UpdateView):
    permission_required = "inventario.change_subcategory"
    model = Subcategory
    template_name = "inventario/subcategoryForm.html"
    context_object_name = "obj"
    form_class = SubcategoryForm
    success_url = reverse_lazy("inventario:subcategoryList")
    login_url = "bases:login"
    success_message="Subcategory Successfully Updated"
    
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

class DeleteSubcategory(NoPermission, generic.DeleteView):
    permission_required = "inventario.delete_subcategory"
    model = Subcategory
    template_name = 'inventario/deleteSubcategory.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inventario:subcategoryList')
    login_url = "bases:login"

class BrandView(NoPermission, generic.ListView):
    permission_required = "inventario.view_brand"
    model = Brand
    template_name = 'inventario/brandList.html'
    context_object_name = "obj"

class NewBrand(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "inventario.add_brand"
    model = Brand
    template_name = "inventario/brandForm.html"
    context_object_name = "obj"
    form_class = BrandForm
    success_url = reverse_lazy("inventario:brandList")
    login_url = "bases:login"
    success_message="Brand Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class UpdateBrand(SuccessMessageMixin, NoPermission, generic.UpdateView):
    permission_required = "inventario.change_brand"
    model = Brand
    template_name = "inventario/brandForm.html"
    context_object_name = "obj"
    form_class = BrandForm
    success_url = reverse_lazy("inventario:brandList")
    login_url = "bases:login"
    success_message="Brand Successfully Updated"
    
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inventario.change_brand', login_url='bases:noPermission')
def activateBrand(request, id):
    brand = Brand.objects.filter(pk=id).first()
    if not brand:
        return redirect("inventario:brandList")
    if request.method =="GET":
        brand.status = True
        brand.save()
        messages.success(request, 'Brand #' + str(id) + ' Activated')
        return redirect("inventario:brandList")

@login_required(login_url='/login/')
@permission_required('inventario.change_brand', login_url='bases:noPermission')
def deactivateBrand(request, id):
    template_name = 'inventario/deactivateBrand.html'
    context = {}
    brand = Brand.objects.filter(pk=id).first()
    if not brand:
        return HttpResponse('This Brand does not exist: /n Brand #' + str(id))
    if request.method == 'GET':
        context = {'obj': brand}
    if request.method =='POST':
        brand.status = False
        brand.save()
        messages.success(request, 'Brand #' + str(id) + ' Deactivated')
        context = {'obj':'OK'}
        return HttpResponse('Brand deactivated')
    return render(request, template_name, context)

class MeasurementUnitsView(NoPermission, generic.ListView):
    permission_required = "inventario.view_measurementunits"
    model = MeasurementUnits
    template_name = 'inventario/measurementUnitsList.html'
    context_object_name = "obj"

class NewMeasurementUnits(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "inventario.add_measurementunits"
    model = MeasurementUnits
    template_name = "inventario/measurementUnitsForm.html"
    context_object_name = "obj"
    form_class = MeasurementUnitsForm
    success_url = reverse_lazy("inventario:measurementUnitsList")
    login_url = "bases:login"
    success_message="Unit Of Measurement Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class UpdateMeasurementUnits(SuccessMessageMixin, NoPermission, generic.UpdateView):
    permission_required = "inventario.change_measurementunits"
    model = MeasurementUnits
    template_name = "inventario/measurementUnitsForm.html"
    context_object_name = "obj"
    form_class = MeasurementUnitsForm
    success_url = reverse_lazy("inventario:measurementUnitsList")
    login_url = "bases:login"
    success_message="Unit Of Measurement Successfully Updated"
    
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inventario.change_measurementunits', login_url='bases:noPermission')
def activateMeasurementUnits(request, id):
    mu = MeasurementUnits.objects.filter(pk=id).first()
    if not mu:
        return redirect("inventario:measurementUnitsList")
    if request.method =="GET":
        mu.status = True
        mu.save()
        messages.success(request, 'Unit of Measurement #' + str(id) + ' Activated')
        return redirect("inventario:measurementUnitsList")

@login_required(login_url='/login/')
@permission_required('inventario.change_measurementunits', login_url='bases:noPermission')
def deactivateMeasurementUnits(request, id):
    template_name = 'inventario/deactivateMU.html'
    context = {}
    mu = MeasurementUnits.objects.filter(pk=id).first()
    if not mu:
        return HttpResponse('This Unit of Measurement does not exist: /n Unit of Measurement #' + str(id))
    if request.method == 'GET':
        context = {'obj': mu}
    if request.method =='POST':
        mu.status = False
        mu.save()
        messages.success(request, 'Unit of Measurement #' + str(id) + ' Deactivated')
        context = {'obj':'OK'}
        return HttpResponse('Unit of Measurement deactivated')
    return render(request, template_name, context)

class ProductView(NoPermission, generic.ListView):
    permission_required = "inventario.view_product"
    model = Product
    template_name = 'inventario/productList.html'
    context_object_name = "obj"

class NewProduct(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "inventario.add_product"
    model = Product
    template_name = "inventario/productForm.html"
    context_object_name = "obj"
    form_class = ProductForm
    success_url = reverse_lazy("inventario:productList")
    login_url = "bases:login"
    success_message="Product Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(NewProduct, self).get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["subcategories"] = Subcategory.objects.all()
        return context

inventario/templates/inventario/brandList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Brand List</h5>
        <!--<div class="dropdown no-arrow">
            Actions
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Actions</div>
                <a class="dropdown-item" onclick="return openModal('{% url 'inventario:newBrand' %}')" href="#"><i class="far fa-calendar-plus"></i> New</a>
            </div>
        </div>-->
    </div>
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% else %}
        <div class="buttons-toolbar">
            <a class="btn" onclick="return openModal('{% url 'inventario:newBrand' %}')" href="#"><i class="fa fa-plus"></i> New</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th>Id</th>
                <th>Brand</th>
                <th>Status</th>
                <th>Creation Date</th>
                <th>Modification Date</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.status|yesno:"Active, Inactive" }}</td>
                    <td>{{ item.creationDate|date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.modificationDate|date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <center>
                            <button onclick="return openModal('{% url 'inventario:updateBrand' item.id %}')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button>
                            <a href="{% url 'inventario:activateBrand' item.id %}" class="btn btn-success btn-circle" role="button"><i class="far fa-thumbs-up"></i></a>
                            <button onclick="return openModal('{% url 'inventario:deactivateBrand' item.id %}')" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></button>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock page_content %} {% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    /*$(document).ready(function() {
        $('.table').DataTable();
    });*/
</script>
<script src="https://www.w3schools.com/lib/w3.js"></script>
{% endblock js_page %}

inventario/templates/inventario/deleteCatalogs.html
{% extends 'base/base.html' %}{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="auto">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-s text-black font-weight-bold text-uppercase mb-1" style="text-align: center">
                            Are you sure that you want to delete "{{ obj.description }}"?
                        </div>
                        <center>
                            <button type="submit" class="btn btn-success"><i class="fas fa-trash"></i> Yes, delete</button>
                            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger"><span class="fa fa-times"></span> Cancel</a>
                        </center>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-exclamation-triangle fa-2x text-danger"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock page_content %}{% block js_page %}{% endblock js_page %}

inventario/templates/inventario/measurementUnitsList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Measurement Units List</h5>
        <!--<div class="dropdown no-arrow">
            Actions
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Actions</div>
                <a class="dropdown-item" href="{% url 'inventario:newMeasurementUnits' %}"><i class="far fa-calendar-plus"></i> New</a>
            </div>
        </div>-->
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% else %}
        <div class="buttons-toolbar">
            <a class="btn" onclick="return openModal('{% url 'inventario:newMeasurementUnits' %}')" href="#"><i class="fa fa-plus"></i> New</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th>Id</th>
                <th>Unit</th>
                <th>Status</th>
                <th>Creation Date</th>
                <th>Modification Date</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.status|yesno:"Active, Inactive" }}</td>
                    <td>{{ item.creationDate|date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.modificationDate|date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <center>
                            <button onclick="return openModal('{% url 'inventario:updateMeasurementUnits' item.id %}')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button>
                            <a href="{% url 'inventario:activateMeasurementUnits' item.id %}" class="btn btn-success btn-circle" role="button"><i class="far fa-thumbs-up"></i></a>
                            <button onclick="return openModal('{% url 'inventario:deactivateMeasurementUnits' item.id %}')" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></button>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock page_content %} {% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    /*$(document).ready(function() {
        $('.table').DataTable();
    });*/
</script>
{% endblock js_page %}

inventario/templates/inventario/productForm.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:updateProduct' obj.pk %}">
            {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'inventario:newProduct' %}">
                {% endif %}
                <div class="col-xl-12 col-md-12 mb-12">
                    {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                        {% else %}
                        <div class="card border-left-success shadow h-100 py-2">
                            {% endif %}
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-s font-weight-bold text-primary text-uppercase mb-1" style="text-align: center;">
                                            {% if obj %} Edit {% else %} New {% endif %} Product
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{  form.code.label  }}</div>
                                                <div class="col-md-6">{{  form.code  }}</div>
                                            </div>
                
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{  form.barCode.label  }}</div>
                                                <div class="col-md-6">{{  form.barCode  }}</div>    
                                            </div>                            
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{  form.description.label  }}</div>
                                                <div class="col-md-6">{{  form.description  }}</div>
                                            </div>
                
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{  form.status.label  }}</div>
                                                <div class="col-md-6">{{  form.status  }}</div>    
                                            </div>                            
                                        </div>
                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.price.label }}</div>
                                                <div class="col-md-6">{{ form.price }}</div>
                                            </div>
                
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.stock.label }}</div>
                                                <div class="col-md-6">{{ form.stock }}</div>    
                                            </div>                            
                                        </div>
                
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="col-md-6">{{ form.lastPurchase.label }}</div>
                                                <div class="col-md-6">{{ form.lastPurchase }}</div>
                                            </div>
                
                                            <div class="col-md-4">
                                                <div class="col-md-6">{{ form.brand.label }}</div>
                                                <div class="col-md-6">{{ form.brand }}</div>    
                                            </div>     
                                            <div class="col-md-4">
                                                <div class="col-md-6">{{ form.measurementUnits.label }}</div>
                                                <div class="col-md-6">{{ form.measurementUnits }}</div>    
                                            </div>                        
                                        </div>
                
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="col-md-6">Category</div>
                                                <div class="col-md-6">
                                                    <select name="category" id="id_category" class="form-control form-control-sm">
                                                        <option value="0">-------</option>
                                                        {% for item in categories %}
                                                            <option value="{{ item.id }}">{{ item.description }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                            </div>
                
                                            <div class="col-md-6">
                                                <div class="col-md-6">Subcategory</div>
                                                <div class="col-md-6">
                                                    <select name="subcategory" id="id_subcategory" class="form-control form-control-sm">
                                                        <option value="0">-------</option>
                                                        {% for item in subcategories %}
                                                            <option value="{{ item.id }}" data-chained="{{ item.category.id }}">{{ item.description }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                            </div>                           
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            <div class="col">
                                                <center>
                                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Save</button>
                                                    <button type="button" class="btn btn-danger" onclick="return closeModal()"><span class="fa fa-times"></span> Cancel</button>
                                                </center>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
            </div>
    </div>
<script>
    $(function(){
        $("#id_category").val("{{ obj.subcategory.category.id }}").change();
        $("#id_subcategory").val("{{ obj.subcategory.id }}").change();
        $("#id_subcategory").chained("#id_category");
    });
</script>