api/urls.py
from django.urls import path, include
from .views import ProductList, ProductDetail

urlpatterns = [
    path('v1/products/', ProductList.as_view(), name='productList'),
    path('v1/products/<str:code>', ProductDetail.as_view(), name='productDetail'),
]

appCYF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

compras/urls.py
from django.urls import path
from compras.views import SupplierView, NewSupplier, UpdateSupplier, deactivateSuppliers, \
    AcquisitionView, acquisition, AcquisitionDetailDelete
from .reports import acquisitionsReport, printAcquisition

urlpatterns = [
    path('supplier/', SupplierView.as_view(), name="supplierList"),
    path('supplier/new', NewSupplier.as_view(), name="newSupplier"),
    path('supplier/edit/<int:pk>', UpdateSupplier.as_view(), name="updateSupplier"),
    path('supplier/deactivate/<int:id>', deactivateSuppliers, name="deactivateSuppliers"),

    path('acquisition/', AcquisitionView.as_view(), name="acquisitionList"),
    path('acquisition/new', acquisition, name="acquisitionNew"),
    path('acquisition/edit/<int:acquisition_id>', acquisition, name="updateAcquisition"),
    path('acquisition/<int:acquisition_id>/delete/<int:pk>', AcquisitionDetailDelete.as_view(), name="deleteAcquisition"),

    path('acquisition/list', acquisitionsReport, name='printAllAcquisitions'),
    path('acquisition/<int:acquisition_id>/print', printAcquisition, name='printOneAcquisition'),
]

compras/models.py
from django.db import models
from bases.models import ModelClass
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum
from inventario.models import Product

class Supplier(ModelClass):
    description = models.CharField(
        max_length=100,
        unique=True
    )
    address = models.CharField(
        max_length=250,
        null=False, 
        blank=True
    )
    contact = models.CharField(
        max_length=100
    )
    phone = models.CharField(
        max_length=10,
        null=True,
        blank=True
    )
    email = models.CharField(
        max_length=250,
        null=True,
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(Supplier, self).save()

    class Meta:
        verbose_name_plural = "Suppliers"

class AcquisitionHeader(ModelClass):
    acquisitionDate = models.DateField(null=True, blank= True)
    observation = models.TextField(blank=True, null=True)
    billNumber = models.CharField(max_length=100)
    billDate = models.DateField()
    subtotal = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total = models.FloatField(default=0)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.observation)
    def save(self):
        self.observation = self.observation.upper()
        self.total = self.subtotal - self.discount
        super(AcquisitionHeader, self).save()
    class Meta:
        verbose_name_plural = "Acquisitions Header"
        verbose_name = "Acquisition Header"

class AcquisitionDetail(ModelClass):
    acquisition = models.ForeignKey(AcquisitionHeader, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.BigIntegerField(default=0)
    supplierPrice = models.FloatField(default=0)
    subtotal = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total = models.FloatField(default=0)
    cost = models.FloatField(default=0)
    def __str__(self):
        return '{}'.format(self.product)
    def save(self):
        self.subtotal = float(float(int(self.amount)) * float(self.supplierPrice))
        self.total = self.subtotal - float(self.discount)
        super(AcquisitionDetail, self).save()
    class Meta:
        verbose_name_plural = "Acquisitions Header"
        verbose_name = "Acquisition Header"

@receiver(post_delete, sender = AcquisitionDetail)
def acquisitionDetailDelete(sender, instance, **kwargs):
    id_product = instance.product.id
    id_acquisition = instance.acquisition.id 
    header = AcquisitionHeader.objects.filter(pk = id_acquisition).first()
    if header:
        subtotal = AcquisitionDetail.objects.filter(acquisition = id_acquisition).aggregate(Sum('subtotal'))
        discount = AcquisitionDetail.objects.filter(acquisition = id_acquisition).aggregate(Sum('discount'))
        header.subtotal = subtotal['subtotal__sum']
        header.discount = discount['discount__sum']
        header.save()
    product = Product.objects.filter(pk = id_product).first()
    if product:
        amount = int(product.stock) - int(instance.amount)
        product.stock = amount
        product.save()

@receiver(post_save, sender = AcquisitionDetail)
def acquisitionDetailSave(sender, instance, **kwargs):
    id_product = instance.product.id
    acquisitionDate = instance.acquisition.acquisitionDate
    product = Product.objects.filter(pk = id_product).first()
    if product:
        amount = int(product.stock) + int(instance.amount)
        product.stock = amount
        product.lastPurchase = acquisitionDate
        product.save()

compras/forms.py
from django import forms
from compras.models import Supplier, AcquisitionHeader, AcquisitionDetail

class SupplierForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)
    class Meta:
        model = Supplier
        exclude = ['creationDate', 'modificationDate', 'userModifier', 'userCreator']
        widget = {'Description': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
    def clean(self):
        try:
            sc = Supplier.objects.get(
                description = self.cleaned_data["description"].upper()
            )
            if not self.instance.pk:
                raise forms.ValidationError("This register already exist")
            elif self.instance.pk != sc.pk:
                raise forms.ValidationError("Change not permited")
        except Supplier.DoesNotExist:
            pass
        return self.cleaned_data

class AcquisitionHeaderForm(forms.ModelForm):
    aquisitionDate = forms.DateInput()
    billDate = forms.DateInput()
    class Meta:
        model = AcquisitionHeader
        fields = ['supplier', 'acquisitionDate', 'observation',
                'billNumber', 'billDate', 'subtotal', 'discount', 
                'total']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['acquisitionDate'].widget.attrs['readonly'] = True
        self.fields['billDate'].widget.attrs['readonly'] = True
        self.fields['subtotal'].widget.attrs['readonly'] = True
        self.fields['discount'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

compras/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Supplier, AcquisitionDetail, AcquisitionHeader
from inventario.models import Product
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
import json
import datetime
from compras.forms import SupplierForm, AcquisitionHeaderForm
from django.urls import reverse_lazy
from bases.views import NoPermission
from django.contrib import messages
from django.db.models import Sum
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required

class SupplierView(NoPermission, generic.ListView):
    permission_required = "compras.view_supplier"
    model = Supplier
    template_name = 'compras/supplierList.html'
    context_object_name = "obj"

class NewSupplier(SuccessMessageMixin, NoPermission, generic.CreateView):
    permission_required = "compras.add_supplier"
    model = Supplier
    template_name = "compras/supplierForm.html"
    context_object_name = "obj"
    form_class = SupplierForm
    success_url = reverse_lazy("compras:supplierList")
    login_url = "bases:login"
    success_message="Supplier Successfully Created"
    
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class UpdateSupplier(SuccessMessageMixin, NoPermission, generic.UpdateView):
    permission_required = "compras.change_supplier"
    model = Supplier
    template_name = "compras/supplierForm.html"
    context_object_name = "obj"
    form_class = SupplierForm
    success_url = reverse_lazy("compras:supplierList")
    login_url = "bases:login"
    success_message="Supplier Successfully Updated"
    
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('compras.change_supplier', login_url='bases:noPermission')
def deactivateSuppliers(request, id):
    template_name = 'compras/deactivateSuppliers.html'
    context = {}
    supplier = Supplier.objects.filter(pk=id).first()
    if not supplier:
        return HttpResponse('This supplier does not exist: /n Supplier #' + str(id))
    if request.method == 'GET':
        context = {'obj': supplier}
    if request.method =='POST':
        supplier.status = False
        supplier.save()
        messages.success(request, 'Supplier #' + str(id) + ' Deactivated')
        context = {'obj':'OK'}
        return HttpResponse('Supplier deactivated')
    return render(request, template_name, context)

class AcquisitionView(NoPermission, generic.ListView):
    permission_required = "compras.view_acquisitionheader"
    model = AcquisitionHeader
    template_name = 'compras/acquisitionList.html'
    context_object_name = "obj"

@login_required(login_url='/login/')
@permission_required('compras.view_acquisitionheader', login_url='bases:noPermission')
def acquisition(request, acquisition_id=None):
    template_name = "compras/acquisition.html"
    product = Product.objects.filter(status=True)
    form_acquisition = {}
    context = {}
    if request.method =='GET':
        form_acquisition = AcquisitionHeaderForm()
        header = AcquisitionHeader.objects.filter(pk = acquisition_id).first()
        if header:
            detail = AcquisitionDetail.objects.filter(acquisition = header)
            acquisitionDate = datetime.date.isoformat(header.acquisitionDate)
            billDate = datetime.date.isoformat(header.billDate)
            e = {
                'acquisitionDate': acquisitionDate,
                'supplier': header.supplier,
                'observation': header.observation,
                'billNumber': header.billNumber,
                'billDate': billDate,
                'subtotal': header.subtotal,
                'discount': header.discount,
                'total': header.total,
            }
            form_acquisition = AcquisitionHeaderForm(e)
        else:
            detail = None
        context = {'products': product,
                    'header': header,
                    'detail': detail,
                    'form_header': form_acquisition,}
    if request.method == 'POST':
        acquisitionDate = request.POST.get("acquisitionDate")
        observation = request.POST.get("observation")
        billNumber = request.POST.get("billNumber")
        billDate = request.POST.get("billDate")
        supplier = request.POST.get("supplier")
        subtotal = 0
        discount = 0
        total = 0
        if not acquisition_id:
            supplier = Supplier.objects.get(pk = supplier)
            header = AcquisitionHeader(
                acquisitionDate = acquisitionDate,
                observation = observation,
                billNumber = billNumber,
                billDate = billDate,
                supplier = supplier,
                userCreator = request.user
            )
            if header:
                header.save()
                acquisition_id = header.id
        else:
            header = AcquisitionHeader.objects.filter(pk = acquisition_id).first()
            if header:
                header.acquisitionDate = acquisitionDate
                header.observation = observation
                header.billNumber = billNumber
                header.billDate = billDate
                header.userModifier = request.user.id
                header.save()
        if not acquisition_id:
            return redirect("compras:acquisitionList")
        product = request.POST.get("id_id_product")
        amount = request.POST.get("id_amount_detail")
        price = request.POST.get("id_price_detail")
        subtotalDetail = request.POST.get("id_subtotal_detail")
        discountDetail = request.POST.get("id_discount_detail")
        totalDetail = request.POST.get("id_total_detail")
        product = Product.objects.get(pk = product)
        detail = AcquisitionDetail(
            acquisition = header,
            product = product,
            amount = amount,
            supplierPrice = price,
            discount = discountDetail,
            cost = 0,
            userCreator = request.user
        )
        if detail:
            detail.save()
            subtotal = AcquisitionDetail.objects.filter(acquisition = acquisition_id).aggregate(Sum('subtotal'))
            discount = AcquisitionDetail.objects.filter(acquisition = acquisition_id).aggregate(Sum('discount'))
            header.subtotal = subtotal["subtotal__sum"]
            header.discount = discount["discount__sum"]
            header.save()
        return redirect("compras:updateAcquisition", acquisition_id = acquisition_id)
    return render(request, template_name, context)

class AcquisitionDetailDelete(NoPermission, generic.DeleteView):
    permission_required = "compras.delete_acquisitiondetail"
    model = AcquisitionDetail
    template_name = "compras/acquisitionDetailDelete.html"
    context_object_name = 'obj'
    def get_success_url(self):
        acquisition_id = self.kwargs['acquisition_id']
        return reverse_lazy('compras:updateAcquisition', kwargs = {'acquisition_id': acquisition_id})

compras/templates/compras/acquisitionDetailDelete.html
<div class="modal-dialog modal-auto">
    <div class="modal-content">
        <form role="form" action="{% url 'compras:deleteAcquisition' obj.acquisition.id obj.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Delete Detail
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            Delete {{ obj.product }} from acquisition number {{ obj.acquisition.id}}?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <center>
                                    <button type="submit" class="btn btn-success"><span class="fas fa-trash"></span> Yes, Delete</button>
                                    <button type="button" class="btn btn-danger" onclick="return closeModal()"><span class="fas fa-times"></span> Cancel</button>
                                </center>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-exclamation-triangle fa-2x text-danger"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

compras/templates/compras/acquisitionList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Acquisition List</h5>
        <!--<div class="dropdown no-arrow">
            Actions
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Actions</div>
                <a class="dropdown-item" href="{% url 'compras:acquisitionNew' %}"><i class="far fa-calendar-plus"></i> New</a>
                <a class="dropdown-item" href="{% url 'compras:printAllAcquisitions' %}" target="reports"><i class="fas fa-print"></i> List</a>
            </div>
        </div>-->
    </div>
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% else %}
        <div class="buttons-toolbar">
            <a class="btn" onclick="return openModal('{% url 'compras:acquisitionNew' %}')" href="#"><i class="fa fa-plus"></i> New</a>
            <a class="btn" href="{% url 'compras:printAllAcquisitions' %}" target="reports"><i class="fas fa-print"></i> Print All</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th>ID</th>
                <th>Acquisition Date</th>
                <th>Observation</th>
                <th>Bill Number</th>
                <th>Bill Date</th>
                <th>Subtotal</th>
                <th>Discount</th>
                <th>Total</th>
                <th>Status</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.acquisitionDate }}</td>
                    <td>{{ item.observation }}</td>
                    <td>{{ item.billNumber }}</td>
                    <td>{{ item.billDate }}</td>
                    <td>{{ item.subtotal }}</td>
                    <td>{{ item.discount }}</td>
                    <td>{{ item.total }}</td>
                    <td>{{ item.status|yesno:"Active, Inactive" }}</td>
                    <td>
                        <center>
                            <a class='btn btn-warning btn-circle' href="{% url 'compras:updateAcquisition' item.id %}"><i class="far fa-edit"></i></a>
                            <a class='btn btn-success btn-circle' href="{% url 'compras:printOneAcquisition' item.id %}" target="reports"><i class="fas fa-print"></i></a>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock page_content %} {% block js_page %}
<script>
    /*$(document).ready(function() {
        $('.table').DataTable();
    });*/
</script>
{% endblock js_page %}

compras/templates/compras/deactivateSuppliers.html
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="auto">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-s text-black font-weight-bold text-uppercase mb-1" style="text-align: center">
                                    <div class="alert">
                                        Are you sure that you want to deactivate <b>"{{ obj.description }}"<b>?
                                    </div>
                                </div>
                                <center>
                                    <button type="button" class="btn btn-success" id="btnDeactivate"><i class="fas fa-trash"></i> Yes, Deactivate</button>
                                    <button type="button" class="btn btn-danger" onclick="return closeModal()"><span class="fa fa-times"></span> Cancel</button>
                                </center>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-exclamation-triangle fa-2x text-danger"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
        var token = $('input[name = csrfmiddlewaretoken]').val();
        $.ajaxSetup({
            beforeSend:function(xhr, settings){
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
                    xhr.setRequestHeader("X-CSRFToken", token);
                }
            }
        });

        $("#btnDeactivate").click(function(e){
            e.preventDefault();
            var id = {{ obj.id }};
            var template = "{% url 'compras:deactivateSuppliers' obj.id %}";
            var data = {"id": id};
            data = JSON.stringify(data);
            $.ajax({
                type:"POST",
                url: template,
                data: data,
                beforeSend: function(xhr, settings){
                    $.ajaxSettings.beforeSend(xhr, settings);
                },
                success: function(response){
                    closeModal();                    
                    location.reload();
                },
                error:function(jqXHR, textStatus, errorThrow){
                    closeModal();
                }
            })   
        });
    });
</script>

compras/templates/compras/printAllAcquisitions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acquisition List</title>
    <style type="text/css">
    @page{
        size: letter;
        margin: 1cm;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
    }
    .table th,
    .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
    }
    .table tbody + tbody {
        border-top: 2px solid #000;
    }
    .table .table {
        background-color: #fff;
    }
    .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                    <h2>MASH ACQUISITION SYSTEM</h2>
                </center>
                <h3>Acquisition Report to {{ today }}</h3>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Acquisition Number</th>
                        <th>Supplier</th>
                        <th>Date</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.supplier }}</td>
                        <td>{{ item.acquisitionDate }}</td>
                        <td>${{ item.total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

compras/templates/compras/supplierForm.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compras:updateSupplier' obj.pk %}">
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compras:newSupplier' %}">
        {% endif %}
                <div class="col-xl-12 col-md-12 mb-12">
                    {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                        {% else %}
                        <div class="card border-left-success shadow h-100 py-2">
                            {% endif %}
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-s font-weight-bold text-primary text-uppercase mb-1" style="text-align: center;">
                                            {% if obj %} Edit {% else %} New {% endif %} Supplier
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        {% csrf_token %}
                                        <div class="row">
                                            {{ form.as_p }}
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            <div class="col">
                                                <center>
                                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Save</button>
                                                    <button type="button" class="btn btn-danger" onclick="return closeModal()"><span class="fa fa-times"></span> Cancel</button>
                                                </center>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </form>
    </div>
</div>
<script>
    var url = $("form").attr("action");
    var token = jQuery("[name-csrfmiddlewaretoken]").val();
    $(function(){
        $("form").submit(function(e){
            e.preventDefault();
            var formData = $("form").serializeArray();
            $.ajax({
                url:url,
                method:"POST",
                headers:{'X-CSRFToken': token},
                data:formData
            })
            .done(function(r, textStatus, xhr){
                if(xhr.status=200){
                    location.reload(true);
                }else{
                    message(textStatus);
                }
            })
            .fail(function(error){
                message(error.responseText);
            });
        });
    });
</script>

compras/templates/compras/supplierList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Supplier List</h5>
        <!--<div class="dropdown no-arrow">
            Actions
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Actions</div>
                <a class="dropdown-item" onclick="return openModal('{% url 'compras:newSupplier' %}')" href="#"><i class="far fa-calendar-plus"></i> New</a>
            </div>
        </div>-->
    </div>
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% else %}
        <div class="buttons-toolbar">
            <a class="btn" onclick="return openModal('{% url 'compras:newSupplier' %}')" href="#"><i class="fa fa-plus"></i> New</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th>ID</th>
                <th>Description</th>
                <th>Address</th>
                <th>Contact</th>
                <th>Phone</th>
                <th>EMail</th>
                <th>Status</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.address }}</td>
                    <td>{{ item.contact }}</td>
                    <td>{{ item.phone }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{ item.status|yesno:"Active, Inactive" }}</td>
                    <td>
                        <center>
                            <button onclick="return openModal('{% url 'compras:updateSupplier' item.id %}')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button>
                            <button onclick="return openModal('{% url 'compras:deactivateSuppliers' item.id %}')" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></button>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock page_content %} {% block js_page %}
<script>
    /* Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('.table').DataTable();
    });*/
</script>
{% endblock js_page %}