api/urls.py
from django.urls import path, include
from .views import ProductList, ProductDetail

urlpatterns = [
    path('v1/products/', ProductList.as_view(), name='productList'),
    path('v1/products/<str:code>', ProductDetail.as_view(), name='productDetail'),
]

appCYF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

facturacion/urls.py
from django.urls import path, include
from .views import CustomerView, NewCustomer, UpdateCustomer, deactivateCustomer, \
    BillingView, billings, \
    ProductView, \
    deleteBillingDetail
from .reports import printBillingReceipt, printBillingList

urlpatterns = [
    path('customer/', CustomerView.as_view(), name="customerList"),
    path('customer/new', NewCustomer.as_view(), name="newCustomer"),
    path('customer/<int:pk>', UpdateCustomer.as_view(), name="updateCustomer"),
    path('customer/status/<int:id>', deactivateCustomer, name="deactivateCustomer"),

    path('billing/', BillingView.as_view(), name="billingList"),
    path('billing/new', billings, name="newBilling"),
    path('billing/edit/<int:id>', billings, name="updateBilling"),

    path('billing/searchProduct', ProductView.as_view(), name="productBilling"),

    path('billing/deleteDetail/<int:id>', deleteBillingDetail, name="deleteBillingDetail"),

    path('billing/print/<int:id>', printBillingReceipt, name="printOneBilling"),
    path('billing/printAll/<str:date1>/<str:date2>', printBillingList, name="printBillingList"),
]

facturacion/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum
from bases.models import ModelClass, ModelClass2
from inventario.models import Product

class Customer(ModelClass):
    NAT = 'Natural'
    JUR = 'Juristic'
    CUSTOMER_TYPE = [
        (NAT, 'Natural'),
        (JUR, 'Juristic')
    ]
    names = models.CharField(max_length=100) 
    lastNames = models.CharField(max_length=100)
    phone = models.CharField(
        max_length=20, 
        null=True, 
        blank=True)
    customerType = models.CharField(
        max_length=10,
        choices=CUSTOMER_TYPE,
        default=NAT
    )
    def __str__(self):
        return '{} {}'.format(self.lastNames, self.names)
    def save(self):
        self.names = self.names.upper()
        self.lastNames = self.lastNames.upper()
        super(Customer, self).save()
    class Meta:
        verbose_name_plural = "Customers"

class BillingHeader(ModelClass2):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    subtotal = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total = models.FloatField(default=0)
    def __str__(self):
        return '{}'.format(self.id)
    def save(self):
        self.total = self.subtotal - self.discount
        super(BillingHeader, self).save()
    class Meta:
        verbose_name_plural = "Billings Header"
        verbose_name = "Billing Header"
        permissions = [
            ('cashier_supervisor_billingheader', 'Cashier Supervisor Permissions')
        ]

class BillingDetail(ModelClass2):
    billing = models.ForeignKey(BillingHeader, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.BigIntegerField(default=0)
    price = models.FloatField(default=0)
    subtotal = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total = models.FloatField(default=0)
    def __str__(self):
        return '{}'.format(self.product)
    def save(self):
        self.subtotal = float(float(int(self.amount)) * float(self.price))
        self.total = self.subtotal - float(self.discount)
        super(BillingDetail, self).save()
    class Meta:
        verbose_name_plural = "Billings Details"
        verbose_name = "Billing Detail"
        permissions = [
            ('cashier_supervisor_billingdetail', 'Cashier Supervisor Permissions')
        ]

@receiver(post_save, sender = BillingDetail)
def billingDetailSave(sender, instance, **kwargs):
    billingId = instance.billing.id
    productId = instance.product.id
    head = BillingHeader.objects.get(pk=billingId)
    if head:
        subtotal = BillingDetail.objects\
            .filter(billing=billingId)\
            .aggregate(subtotal=Sum('subtotal'))\
            .get('subtotal', 0.00)
        discount = BillingDetail.objects\
            .filter(billing=billingId)\
            .aggregate(discount=Sum('discount'))\
            .get('discount', 0.00)
        head.subtotal = subtotal
        head.discount = discount
        head.save()
    product = Product.objects.filter(pk=productId).first()
    if product:
        amount = int(product.stock) - int(instance.amount)
        product.stock = amount
        product.save()

facturacion/forms.py
from django import forms
from .models import Customer

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['names', 'lastNames', 'customerType',
                'phone', 'status']
        exclude = ['creationDate', 'modificationDate', 
                'userModifier', 'userCreator']
        widget = {'description': forms.TextInput()}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

facturacion/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required, permission_required
from .forms import CustomerForm
from .models import Customer, BillingDetail, BillingHeader, Product
from bases.views import NoPermission
import inventario.views as inv
from django.contrib import messages
from django.contrib.auth import authenticate

class CustomerView(NoPermission, generic.ListView):
    model = Customer
    template_name = "facturacion/customerList.html"
    context_object_name = "obj"
    permission_required = "compras.view_customer"

class MainCreateView(SuccessMessageMixin, NoPermission, generic.CreateView):
    context_object_name = 'obj'
    success_message = "Register Added Successfully"
    def form_valid(self, form):
        form.instance.userCreator = self.request.user
        return super().form_valid(form)

class MainUpdateView(SuccessMessageMixin, NoPermission, generic.UpdateView):
    context_object_name = 'obj'
    success_message = "Register Updated Successfully"
    def form_valid(self, form):
        form.instance.userModifier = self.request.user.id
        return super().form_valid(form)

class NewCustomer(MainCreateView):
    model = Customer
    template_name = "facturacion/customerForm.html"
    form_class = CustomerForm
    success_url = reverse_lazy("facturacion:customerList")
    permission_required = "facturacion.add_customer"

class UpdateCustomer(MainUpdateView):
    model = Customer
    template_name = "facturacion/customerForm.html"
    form_class = CustomerForm
    success_url = reverse_lazy("facturacion:customerList")
    permission_required = "facturacion.change_customer"

@login_required(login_url="/login/")
@permission_required("facturacion.change_customer", login_url="/login/")
def deactivateCustomer(request, id):
    customer = Customer.objects.filter(pk=id).first()
    if request.method == "POST":
        if customer:
            customer.status = not customer.status
            customer.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    return HttpResponse("FAIL")

class BillingView(NoPermission, generic.ListView):
    model = BillingHeader
    template_name = "facturacion/billingList.html"
    context_object_name = "obj"
    permission_required = "facturacion.view_billingheader"

@login_required(login_url="/login/")
@permission_required("facturacion.change_billingheader", login_url='bases:NoPermission')
def billings(request, id=None):
    template_name = 'facturacion/billings.html'
    detail = {}
    customers = Customer.objects.filter(status=True)
    if request.method == "GET":
        head = BillingHeader.objects.filter(pk=id).first()
        if not head: 
            header = {
                'id': 0,
                'date': datetime.today(),
                'customer':0,
                'subtotal':0.00,
                'discount':0.00,
                'total': 0.00
            }
            detail=None
        else:
            header = {
                'id': head.id,
                'date': head.date,
                'customer':head.customer,
                'subtotal':head.subtotal,
                'discount':head.discount,
                'total': head.total
            }
        detail = BillingDetail.objects.filter(billing=head)
        context = {"head":header, "det":detail, "customers": customers}
        return render(request, template_name, context)

    if request.method == "POST":
        customer = request.POST.get("headerCustomer")
        date = request.POST.get("date")
        custom = Customer.objects.get(pk=customer)
        if not id:
            head = BillingHeader(
                customer = custom,
                date = date,
            )
            if head:
                head.save()
                id = head.id
        else:
            head = BillingHeader.objects.filter(pk=id).first()
            if head:
                head.customer = custom
                head.save()
        if not id:
            messages.error(request, 'Billing Number has not found')
            return redirect("facturacion:billingList")
        code = request.POST.get("code")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        subtotal = request.POST.get("subtotalDetail")
        discount = request.POST.get("discountDetail")
        total = request.POST.get("totalDetail")
        
        prod = Product.objects.get(code=code)
        det = BillingDetail(
            billing = head,
            product = prod,
            amount = amount,
            price = price,
            subtotal = subtotal,
            discount = discount,
            total = total
        )
        if det:
            det.save()
        return redirect("facturacion:updateBilling", id=id)
    return render(request, template_name, context)

class ProductView(inv.ProductView):
    template_name = "facturacion/searchProduct.html"

def deleteBillingDetail(request, id):
    template_name = "facturacion/deleteBillingDetail.html"
    det = BillingDetail.objects.get(pk=id)
    if request.method == "GET":
        context = {"det":det}
    if request.method == "POST":
        usr = request.POST.get("user") 
        pas = request.POST.get("password")
        user = authenticate(username=usr, password=pas)
        if not user:
            return HttpResponse("Wrong username or password")
        if not user.is_active:
            return HttpResponse("Inactive User")
        if user.is_superuser or user.has_perm("facturas.cashier_supervisor_billingdetail"):
            det.id = None
            det.amount = (-1 * det.amount)
            det.subtotal = (-1 * det.subtotal)
            det.discount = (-1 * det.discount)
            det.total = (-1 * det.total)
            det.save()
            return HttpResponse("ok")
        return HttpResponse("User not allowed")
    return render(request, template_name, context)
    

facturacion/templates/facturacion/allBillings.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Acquisition List</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
    }
    .table th,
    .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
    }
    .table tbody + tbody {
        border-top: 2px solid #000;
    }
    .table .table {
        background-color: #fff;
    }
    .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                    <h4>MASH DEVS</h4>
                    <h3>Billing Report<br><small>Period: {{ date1 | date:"d/m/Y" }} - {{ date2 | date:"d/m/Y" }}</small></h3>
                </center>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>Billing Number</th>
                        <th>Date</th>
                        <th>Customer</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in head %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.date | date:"d/m/Y"  }}</td>
                        <td>{{ item.customer }}</td>
                        <td>{{ item.total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

facturacion/templates/facturacion/billingList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Billing List</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <input type="text" class="form-class" name="date1" id="date1" placeholder="Pick a date" readonly>
            </div>
            <div class="col-md-4">
                <input type="text" class="form-class" name="date2" id="date2" placeholder="Pick a date" readonly>
            </div>
            <div class="col-md-4">
                <button class="btn btn-warning" type="button" id="btnPrint">Print</button>
            </div>
        </div>
        <hr>
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% endif %}
        <div class="buttons-toolbar">
            <a class="btn" href="{% url 'facturacion:newBilling' %}"><i class="fa fa-plus"></i> New</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th data-sortable="true" data-field="id">Bill Number</th>
                <th data-sortable="true" data-field="customer">Customer</th>
                <th data-sortable="true" data-field="total">Total</th>
                <th data-field="status">Status</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.customer }}</td>
                    <td>{{ item.total }}</td>
                    <td>{{ item.status|yesno:"Active, Inactive" }}</td>
                    <td>
                        <center>
                            <a href="{% url 'facturacion:updateBilling' item.id %}" class="href btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock page_content %} 
{% block js_page %}
<script>
    $(function(){
        $("#date1, #date2").datetimepicker({
            format: 'Y-m-d',
            timepicker: false
        });
        $("#btnPrint").click(function(e){
            e.preventDefault();
            var date1, date2;
            date1 = $("#date1").val();
            date2 = $("#date2").val();
            if(date1=="" || date1==null){
                date1 = ""
            }
            if(date2=="" || date2==null){
                var d = new Date();
                var date2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
            }
            var url = "printAll/" + date1 + "/" + date2;
            window.open(url, 'facturas');
        });
    });
</script>
{% endblock js_page %}

facturacion/templates/facturacion/customerForm.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:updateCustomer' obj.pk %}">
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:newCustomer' %}">
            {% endif %}
                <div class="col-xl-12 col-md-12 mb-12">
                    {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                        {% else %}
                        <div class="card border-left-success shadow h-100 py-2">
                            {% endif %}
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-s font-weight-bold text-primary text-uppercase mb-1" style="text-align: center;">
                                            {% if obj %} Edit {% else %} New {% endif %} Customer
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        {% csrf_token %}
                                        <div class="row">
                                            {{ form.as_p }}
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            <div class="col">
                                                <center>
                                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Save</button>
                                                    <button type="button" class="btn btn-danger" onclick="return closeModal()"><span class="fa fa-times"></span> Cancel</button>
                                                </center>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </form>
    </div>
</div>

facturacion/templates/facturacion/customerList.html
{% extends 'base/base.html' %} {% block page_content %}
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5 class="m-0 font-weight-bold text-primary">Customer List</h5>
        <!--<div class="dropdown no-arrow">
            Actions
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Actions</div>
                <a class="dropdown-item" onclick="return openModal('{% url 'facturacion:newCustomer' %}')" href="#"><i class="far fa-calendar-plus"></i> New</a>
            </div>
        </div>-->
    </div>
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">Empty</div>
        {% else %}
        <div class="buttons-toolbar">
            <a class="btn" onclick="return openModal('{% url 'facturacion:newCustomer' %}')" href="#"><i class="fa fa-plus"></i> New</a>
        </div>
        <table 
            data-toggle="table" 
            data-pagination="true" 
            data-search="true" 
            data-show-columns="true" 
            data-show-toggle="true"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th data-sortable="true" data-field="id">ID</th>
                <th data-sortable="true" data-field="names">Names</th>
                <th data-sortable="true" data-field="lastNames">Last Names</th>
                <th data-sortable="true" data-field="customerType">Customer Type</th>
                <th data-sortable="true" data-field="phone">Phone</th>
                <th data-field="status">Status</th>
                <th class="all">Actions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.names }}</td>
                    <td>{{ item.lastNames }}</td>
                    <td>{{ item.customerType }}</td>
                    <td>{{ item.phone }}</td>
                    <td>
                        <div onclick="deactivate({{ item.id }})">
                            {% if item.status %}
                                <i class="far fa-thumbs-up text-success"></i>
                            {% else %}
                                <i class="far fa-thumbs-down text-danger"></i>
                            {% endif %}
                        </div>
                    </td>
                    <td>
                        <center>
                            <button onclick="return openModal('{% url 'facturacion:updateCustomer' item.id %}')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock page_content %} {% block js_page %}
<script>
    function deactivate(id){
        var data = {id:id};
        data = JSON.stringify(data);
        var token = '{{ csrf_token }}';
        $.ajax({
            headers: {"X-CSRFToken": token},
            type: "POST",
            url: "/facturacion/customer/status/" + id,
            data: data,
            success: function(response){
                if(response==="OK"){
                    location.reload(true);
                } else{
                    message("An error has ocurred trying to change the customer status");
                }
            },
            error: function(jqXHR, textStatus, errorThrow){
                console.log(textStatus, errorThrow);
                message(errorThrow, 'red');
                closeModal();
            }
        });
    }
    /* Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('.table').DataTable();
    });*/
</script>
{% endblock js_page %}

facturacion/templates/facturacion/deleteBillingDetail.html
<label class="text">Are you sure you want to delete <b>{{ det.product.description }}</b> from billing <b>{{ det.billing.id }}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">User:</label>
        <input type="text" id="user" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Password:</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

facturacion/templates/facturacion/oneBilling.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>
    <link rel="stylesheet" href="{% static 'base/css/receipt.css' %}">
    <style type="text/css">
        @page {
            width: 58mm; 
            size: auto;   
            margin: 0mm;
        }
    </style>
</head>
<body onload="window.print();window.close()" class="receipt">
    <div class="col-md-1 col-sm-1 col-xs-1 col-xl-1">
        <center>
            <b class="text-center">MASH DEVS</b><br> 
            <small>Address</small><br>
            <small>Billing Number: {{ head.billing }}</small><br>
        </center>
        <small>
            <br>
            <b>Billing Number:</b>&nbsp;&nbsp;{{ head.id }}&nbsp;&nbsp;
            <b>Billing Date:</b>&nbsp;&nbsp;{{ head.date }}&nbsp;&nbsp; <br>
            <b>Customer:</b>&nbsp;&nbsp;{{ head.customer.id }}&nbsp;&nbsp;- {{ head.customer }}<br>
            <br><br>
        </small>
        <table class="table table-condensed table-sm" width="60%">
            <thead>
                <th>Code</th>
                <th  align='right'>Amount</th>
                <th  align='right'>Unit Price</th>
                <th  align='right'>Subtotal</th>
                <th  align='right'>Discount</th>
                <th  align='right'>Total</th>
            </thead>
            <tbody>
                {% for obj in detail %}
                <tr>
                    <td>{{ obj.product.id }}</td>
                    <td>{{ obj.amount }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.subtotal }}</td>
                    <td>{{ obj.discount }}</td>
                    <td>{{ obj.total }}</td>
                </tr>
                <tr>
                    <td colspan="5">{{ obj.product }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-xs-1"></div>
        <div class="col-xs-11">
            <div class="pull-right">
            <table class="table-responsive dt-responsive nowrap">
                <thead>
                    <th colspan=2>Totals</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Subtotal:</td> <td align='right'>{{ head.subtotal }}</td>
                    </tr>
                    <tr>
                        <td>IVA:</td> <td align='right'>{{ head.discount }}</td>
                    </tr>
                    <tr>
                        <td>Total:</td> <td align='right'><b>{{ head.total }}</b></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div class="row">
        <small class="pie">
            <br><br>
            <center>
                Created by:  {{ head.userCreator }} - Fecha:  {{ head.creationDate }}
                <br>
                <i>&copy; &reg; <b>MASH DEVS</b><br> - qk.leugim@gmail.com</i> 
            </center>
        </small>
        </div>
    </div>
</body>
</html>